services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/quotes.json:/app/quotes.json
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 1s
      timeout: 3s
      retries: 30

  client:
    build: 
      context: ./client
    depends_on:
      server:
        condition: service_healthy 